pruebaSem: semaforo.o pruebaSem.cpp
	g++ -g -Wall -o pruebaSem semaforo.o pruebaSem.cpp
semaforo.o: semaforo.cpp semaforo.h
	g++ -g -Wall -c semaforo.o semaforo.cpp
.PHONY: clean
clean:
	rm -rf *.o
